-- ==============================
-- TABLE: Categories
-- ==============================
create table categories (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- Optional: sample categories
insert into categories (name) values 
('Finance'), 
('Environment'), 
('Transport');

-- ==============================
-- TABLE: Areas
-- Hierarchical: wards → community boards → city-wide
-- ==============================
create table areas (
  id bigint generated by default as identity primary key,
  name text not null,
  type text check (type in ('City-wide', 'Community Board', 'Ward')),
  parent_id bigint references areas(id) on delete cascade
);

-- Optional: sample areas
-- City-wide root
insert into areas (name, type) values ('City-wide', 'City-wide');

-- Community boards under City-wide
insert into areas (name, type, parent_id) values
('Papanui-Innes-Central Community Board', 'Community Board', 1),
('Linwood-Central-Heathcote Community Board', 'Community Board', 1);

-- Wards under community boards
insert into areas (name, type, parent_id) values
('Papanui Ward', 'Ward', 2),
('Innes Ward', 'Ward', 2),
('Central Ward', 'Ward', 2),
('Linwood Ward', 'Ward', 3),
('Central Ward', 'Ward', 3),
('Heathcote Ward', 'Ward', 3);

-- ==============================
-- TABLE: Parties
-- ==============================
create table parties (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- Optional: sample parties
insert into parties (name) values 
('Labour'), 
('National'), 
('Green'), 
('Independent');

-- ==============================
-- TABLE: Councillors
-- ==============================
create table councillors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  ward_id bigint references areas(id) on delete set null,
  party_id bigint references parties(id) on delete set null
);

-- Optional: sample councillors
insert into councillors (name, ward_id, party_id) values
('Councillor A', 4, 1),
('Councillor B', 5, 2),
('Councillor C', 6, 4);

-- ==============================
-- TABLE: Motions
-- ==============================
create table motions (
  id bigint generated by default as identity primary key,
  meeting_date date not null,
  title text not null,
  description text,
  category_id bigint references categories(id) on delete set null,
  area_id bigint references areas(id) on delete set null
);

-- Optional: sample motions
insert into motions (meeting_date, title, description, category_id, area_id) values
('2025-08-15', 'Approval of City Budget', 'Annual budget approval for Christchurch City Council', 1, 1),
('2025-07-10', 'Climate Action Plan', 'Vote on adopting the climate action plan for 2030', 2, 2);

-- ==============================
-- TABLE: Votes
-- ==============================
create table votes (
  id bigint generated by default as identity primary key,
  motion_id bigint references motions(id) on delete cascade,
  councillor_id bigint references councillors(id) on delete cascade,
  vote text check (vote in ('For', 'Against', 'Abstain', 'Absent'))
);

-- Optional: sample votes
insert into votes (motion_id, councillor_id, vote) values
(1, 1, 'For'),
(1, 2, 'Against'),
(1, 3, 'For'),
(2, 1, 'Abstain'),
(2, 2, 'For'),
(2, 3, 'For');